#+TITLE: English Wangjian
* ImageNet Training in Minutes 
Background:
- The ImageNet-1k benchmark set has played a significant role as a benchmark for ascertaining the accuracy of different deep neural net (DNN) models on the classification problem. 
- The training time cost is significant. Finishing a 90-epoch ImageNet-1k training with ResNet-50 on a NVIDIA M40 GPU takes 14 days.

Solution:  
- Most successful approaches to scaling ImageNet training have used the synchronous stochastic gradient descent. 
- Enable increasing the batch size in data-parallel
- In this paper, we use LARS algorithm together with warmup scheme to scale up the batch size.

Results:  
- using LARS we efficiently utilized 1024 CPUs to finish the 100-epoch ImageNet training with AlexNet in 11 minutes with 58.6% accuracy (batch size = 32K),
- We utilized 2048 KNLs to finish the 90-epoch ImageNet training with ResNet-50 in 20 minutes without losing accuracy (batch size = 32K).
- State-of-the-art ImageNet training speed with ResNet-50 is 74.9% top-1 test accuracy in 15 minutes. But we got 74.9% top-1 test accuracy in 64 epochs, which only needs 14 minutes.
- Furthermore, when the batch size is above 16K, our accuracy using LARS is much higher than Facebooks corresponding batch sizes 
* Sliding Sketches: A Framework using Time Zones for Data Stream Processing in Sliding Windows SIGKDD 20'
Data stream processing has become a hot issue in recent years due to the arrival of big data era. There are three fundamental stream processing tasks: membership query, frequency query and heavy hitter query. 
* BOI Agents: From Theory to practice
Primary content:
1. the theoretical foundations of BDI agents.
   a. Belief (you know)
   b. Desire (you want to do)
   c. Intention (you can do)
2. the implementations of BDI agents
   a. ideal theoretical perspective
   b. practical perspective
3. the building of large-scale applications based on BDI agens
   eg: an air-traffic management application
* The Design philosophy of the DARPA Internet protoclo
Internet protoclo, TCP/IP , has been widely used, but nobody can deduce from these why the protocol is as it is.
* 
The author proposed emotion-cause pair extraction(ECPE). It's a new task in the Natural Language Processing(NLP). We can detect the emotions or causes in different documents by using a machine-learning method. And the find the potential pairs of emotions and corresponding causes.
